In [1]:
import tensorflow as tf
import numpy as np
import config

In [2]:
np.array([[3,1,1],[1,3,2],[2,3,3],[1,2,3]])

array([[3, 1, 1],
       [1, 3, 2],
       [2, 3, 3],
       [1, 2, 3]])

In [5]:
test=np.array([[3,1,1],[1,3,2],[2,3,3],[1,2,3]])
np.argmax(test,0).shape

array([0, 1, 2])

In [23]:
np.argmax(test,0).shape

(3,)

In [4]:
label=np.array([[3,1,1],[1,3,2],[2,3,3],[1,2,3]])
np.int16(np.equal(label,1))

array([[0, 1, 1],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0]], dtype=int16)

In [6]:
a=[1,4]
b=[2,3]
c=[2,7]
d=[7,4]

In [9]:
np.stack([a,b,c,d],1)

array([[1, 2, 2, 7],
       [4, 3, 7, 4]])

In [10]:
def read_csv(batch_size, file_name, record_defaults):
    filename_queue = tf.train.string_input_producer([config.getProjectRoot() + "/Iris/" + file_name])

    reader = tf.TextLineReader()
    key, value = reader.read(queue=filename_queue)

    # decode_csv will convert a Tensor from type string (the text line) in
    # a tuple of tensor columns with the specified defaults, which also
    # sets the data type for each column
    decoded = tf.decode_csv(value, record_defaults=record_defaults)

    return tf.train.shuffle_batch(decoded, batch_size=batch_size, capacity=batch_size * 50,
                                  min_after_dequeue=batch_size)

In [11]:
sepal_length, sepal_width, petal_length, petal_width, label= read_csv(10, "iris.data", [[0.0], [0.0], [0.0], [0.0], [""]])

In [15]:
tf.transpose(tf.stack([sepal_length, sepal_width, petal_length, petal_width]))

<tf.Tensor 'transpose:0' shape=(10, 4) dtype=float32>

In [18]:
tf.argmax(tf.to_int32(tf.stack(
        [tf.equal(label, ["Iris-setosa"]), tf.equal(label, ["Iris-versicolor"]),
         tf.equal(label, ["Iris-virginica"])])),0)

<tf.Tensor 'ArgMax_1:0' shape=(10,) dtype=int64>

In [17]:
tf.stack(
        [tf.equal(label, ["Iris-setosa"]), tf.equal(label, ["Iris-versicolor"]),
         tf.equal(label, ["Iris-virginica"])])

<tf.Tensor 'stack_4:0' shape=(3, 10) dtype=bool>

In [20]:
sepal_length.shape

TensorShape([Dimension(10)])

In [21]:
tf.stack([sepal_length])

<tf.Tensor 'stack_6:0' shape=(1, 10) dtype=float32>